import { NewsArticle } from "@/types/news";

export const MOCK_ARTICLES: NewsArticle[] = [
  {
    id: "1",
    title: "Global Markets Rally As Tech Stocks Surge To New All-Time Highs",
    slug: "markets-rally",
    excerpt: "Investors are pouring money into AI-driven tech companies, pushing major indices to unprecedented levels despite lingering inflation concerns.",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1200&auto=format&fit=crop",
    category: { name: "Economy", slug: "economy" },
    author: { name: "Sarah Jenkins", slug: "sarah-jenkins", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    readingTime: 4,
    isBreaking: true,
  },
  {
    id: "2",
    title: "Major Scientific Breakthrough in Renewable Energy announced today",
    slug: "renewable-energy",
    excerpt: "A team of international scientists has successfully demonstrated a new solar panel technology that operates at 40% efficiency.",
    image: "https://images.unsplash.com/photo-1509391366360-1f95096efb22?q=80&w=1200&auto=format&fit=crop",
    category: { name: "Technology", slug: "technology" },
    author: { name: "Dr. Alan Turing", slug: "alan-turing", avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=100&h=100&fit=crop" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    readingTime: 6,
  },
  {
    id: "3",
    title: "Championship Finals Set to Break Viewership Records This Weekend",
    slug: "championship-finals",
    excerpt: "The highly anticipated match between the long-time rivals is expected to draw over 100 million viewers globally.",
    image: "https://images.unsplash.com/photo-1508344928928-7157b6868bc2?q=80&w=1200&auto=format&fit=crop",
    category: { name: "Sports", slug: "sports" },
    author: { name: "Mike Tyson", slug: "mike-tyson", avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    readingTime: 3,
  },
  {
    id: "4",
    title: "New AI Model Demonstrates Unprecedented Reasoning Capabilities",
    slug: "new-ai-model",
    excerpt: "The latest breakthrough in artificial intelligence shows the ability to solve complex mathematical proofs previously thought impossible for machines.",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1200&auto=format&fit=crop",
    category: { name: "Technology", slug: "technology" },
    author: { name: "Ada Lovelace", slug: "ada-lovelace", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    readingTime: 8,
  },
  {
    id: "5",
    title: "Historic Climate Agreement Reached at International Summit",
    slug: "climate-agreement",
    excerpt: "Over 190 nations have pledged to reduce carbon emissions by an additional 20% over the next decade in a landmark treaty.",
    image: "https://images.unsplash.com/photo-1611273426858-450d8e8eb15b?q=80&w=1200&auto=format&fit=crop",
    category: { name: "Politics", slug: "politics" },
    author: { name: "Sarah Jenkins", slug: "sarah-jenkins", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    readingTime: 5,
  },
  {
    id: "6",
    title: "The Future of Remote Work: What Companies Are Planning for 2027",
    slug: "future-of-remote-work",
    excerpt: "A new survey reveals that 75% of Fortune 500 companies are moving towards a permanent hybrid model, abandoning strict return-to-office mandates.",
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1200&auto=format&fit=crop",
    category: { name: "Business", slug: "business" },
    author: { name: "John Doe", slug: "john-doe", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop" },
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    readingTime: 7,
  }
];
